select
    cast(get_json_object(payload, '$.id') as bigint) as stat_id,
    cast(get_json_object(payload, '$.player.id') as bigint) as player_id,
    cast(get_json_object(payload, '$.team.id') as bigint) as team_id,
    cast(get_json_object(payload, '$.game.id') as bigint) as game_id,
    get_json_object(payload, '$.min') as minutes_played,
    cast(get_json_object(payload, '$.pts') as double) as pts,
    cast(get_json_object(payload, '$.ast') as double) as ast,
    cast(get_json_object(payload, '$.reb') as double) as reb,
    cast(get_json_object(payload, '$.oreb') as double) as oreb,
    cast(get_json_object(payload, '$.dreb') as double) as dreb,
    cast(get_json_object(payload, '$.stl') as double) as stl,
    cast(get_json_object(payload, '$.blk') as double) as blk,
    cast(get_json_object(payload, '$.turnover') as double) as turnovers,
    cast(get_json_object(payload, '$.pf') as double) as personal_fouls,
    cast(get_json_object(payload, '$.fgm') as double) as fgm,
    cast(get_json_object(payload, '$.fga') as double) as fga,
    cast(get_json_object(payload, '$.fg_pct') as double) as fg_pct,
    cast(get_json_object(payload, '$.fg3m') as double) as fg3m,
    cast(get_json_object(payload, '$.fg3a') as double) as fg3a,
    cast(get_json_object(payload, '$.fg3_pct') as double) as fg3_pct,
    cast(get_json_object(payload, '$.ftm') as double) as ftm,
    cast(get_json_object(payload, '$.fta') as double) as fta,
    cast(get_json_object(payload, '$.ft_pct') as double) as ft_pct,
    cast(ingested_at as timestamp) as ingested_at
from {{ source('nba_staging', 'raw_stats') }}
